import Navbar from "@/components/navbar";
import Head from "next/head";
import { MouseTrail } from "@stichiboi/react-elegant-mouse-trail";
import $ from "jquery";
import { useState, useEffect } from "react";
import styles from "@/styles/alerts.module.css";
import Footer from "@/components/Footer";
import PopupBtn from "@/components/PopupButton";
import AlertData from "@/Data/Alerts.json";
import Parser from 'html-react-parser';
import Live from "@/components/live";

const Announcement = () => {
  const [data, setData] = useState([]);
  const [empty, setEmpty] = useState([]);

  useEffect(() => {
    localStorage.setItem("PrevAlerts", AlertData.length)
  });

  const trailProps = {
    lineDuration: 15,
    lineWidthStart: 10,
    strokeColor: "#EBB935",
    lag: 0,
  };

  return (
    <>
      <Head>
        <title>Alerts | Ignitia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="./css/logosvg.css" />
      </Head>
      <Navbar />
      <div style={{ zIndex: 1000 }}>
        <MouseTrail {...trailProps} />
      </div>
      <PopupBtn />
      <Live />
      <div className={styles.parent}>
        <div style={{ paddingTop: "90px" }} className={styles["section-title"]}>
          <h2>Alerts</h2>
        </div>
        {empty}

        {AlertData.map((single) => {
          return (
            <>
              <div className={styles.alertdiv} onClick={() => { window.open(single.Link) }} id={single.ID}>
                <div id={single.ID * 2}>
                  <img src="/img/Notice.png" width={"20px"} /> {single.Date}
                </div>
                <div id={single.ID}>
                  {Parser(single.Title)}
                </div>
              </div>
            </>
          )
        })}
      </div>
      <Footer />
    </>
  );
};

export default Announcement;
